// Browser check for STEP 5 screens: migrate workbook → FIFO → history → close → roll forward.
import { chromium } from 'playwright';
import path from 'node:path';
const [, , base, wbPath, outDir] = process.argv;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_TUNNEL')) errors.push('console: ' + m.text()); });
page.on('dialog', async (d) => { console.log('dialog:', d.message().slice(0, 120).replace(/\n/g, ' | ')); await d.accept(d.type() === 'prompt' ? 'test' : undefined); });
await page.goto(base + '#settings');
await page.waitForSelector('#f-xlsm', { state: 'attached' });
const t0 = Date.now();
await page.setInputFiles('#f-xlsm', wbPath);
await page.waitForSelector('#mig table', { timeout: 240000 });
console.log('migrate secs', (Date.now() - t0) / 1000);
console.log((await page.textContent('#mig')).replace(/\s+/g, ' ').replace(/.*STEP 4 · Lô bất thường đơn giá/, '…'));
const shot = (n) => page.screenshot({ path: path.join(outDir, n) });
const txt = async (sel) => (await page.textContent(sel)).replace(/\s+/g, ' ');
await page.goto(base + '#cc'); await page.waitForTimeout(400); await shot('30-cc.png');
console.log('CC next:', (await txt('.next')));
await page.goto(base + '#fgopen'); await page.waitForSelector('.kpis'); await shot('31-fgopen.png');
console.log('OPEN:', await txt('.result'), '|', await txt('.kpis'));
await page.goto(base + '#step5'); await page.waitForSelector('.kpis'); await shot('32-step5.png');
console.log('FIFO:', await txt('.result'), '|', await txt('.kpis'));
for (const t of ['detail', 'ledger', 'closing', 'sum', 'rw', 'xnt', 'rec', 'sales']) { await page.click(`[data-tab5="${t}"]`); await page.waitForTimeout(200); if (t === 'rw') await shot('33-rework.png'); }
await page.click('[data-act=s5-run]'); await page.waitForTimeout(1500);
console.log('FIFO rerun:', await txt('.result'), (await txt('main')).match(/Chạy \d.{0,60}/)?.[0]);
await page.goto(base + '#close'); await page.waitForSelector('.result'); await shot('34-close.png');
console.log('CLOSE:', await txt('.result'), '|', await txt('.kpis'));
await page.click('[data-act=s5-hist]'); await page.waitForTimeout(1200);
await page.click('[data-act=s5-close]'); await page.waitForTimeout(1200);
console.log('after close:', await txt('.result'));
await shot('35-closed.png');
await page.goto(base + '#step4'); await page.click('[data-act=run-step4]'); await page.waitForTimeout(500);
await page.evaluate(() => { window.prompt = () => '2026-09'; });
await page.click('[data-act=new-period]'); await page.waitForTimeout(2000);
await page.goto(base + '#fgopen'); await page.waitForSelector('.kpis');
console.log('SEP open:', await txt('.result'), '|', await txt('.kpis'));
await page.click('[data-act=s5-validate]'); await page.waitForTimeout(800);
console.log('SEP validate:', await txt('.result'));
await shot('36-sep-open.png');
await page.goto(base + '#close'); await page.waitForSelector('.kpis');
console.log('SEP hist:', await txt('.kpis'));
await page.goto(base + '#cc'); await page.waitForTimeout(400);
console.log('SEP cc:', (await txt('main')).slice(0, 300));
await page.emulateMedia({ colorScheme: 'dark' }); await page.goto(base + '#step5'); await page.waitForTimeout(400); await shot('37-dark.png');
await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base + '#fgopen'); await page.waitForTimeout(400); await shot('38-mobile.png');
console.log('errors:', errors.join('\n') || 'none');
await browser.close();
