// Browser check for STEP 5 screens: migrate workbook → FIFO → history → close → roll forward.
import { chromium } from 'playwright';
import path from 'node:path';
const [, , base0, wbPath, outDir] = process.argv;
const base = base0 + '?sandbox=1';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_TUNNEL')) errors.push('console: ' + m.text()); });
page.on('dialog', async (d) => { console.log('dialog:', d.message().slice(0, 120).replace(/\n/g, ' | ')); await d.accept(d.type() === 'prompt' ? 'test' : undefined); });
await page.goto(base + '#settings');
await page.waitForSelector('#f-xlsm', { state: 'attached' });
const t0 = Date.now();
await page.setInputFiles('#f-xlsm', wbPath);
await page.waitForSelector('#mig table', { timeout: 240000 });
console.log('migrate secs', (Date.now() - t0) / 1000);
console.log((await page.textContent('#mig')).replace(/\s+/g, ' ').replace(/.*STEP 4 · Lô bất thường đơn giá/, '…'));
const shot = (n) => page.screenshot({ path: path.join(outDir, n) });
const txt = async (sel) => (await page.textContent(sel)).replace(/\s+/g, ' ');
await page.goto(base + '#cc'); await page.waitForTimeout(400); await shot('30-cc.png');
console.log('CC next:', (await txt('.next')));
await page.goto(base + '#fgopen'); await page.waitForSelector('.kpis'); await shot('31-fgopen.png');
console.log('OPEN:', await txt('.result'), '|', await txt('.kpis'));
await page.goto(base + '#step5'); await page.waitForSelector('.kpis'); await shot('32-step5.png');
console.log('FIFO:', await txt('.result'), '|', await txt('.kpis'));
for (const t of ['detail', 'ledger', 'closing', 'sum', 'rw', 'xnt', 'rec', 'sales']) { await page.click(`[data-tab5="${t}"]`); await page.waitForTimeout(200); if (t === 'rw') await shot('33-rework.png'); }
await page.click('[data-act=s5-run]'); await page.waitForTimeout(1500);
console.log('FIFO rerun:', await txt('.result'), (await txt('main')).match(/Chạy \d.{0,60}/)?.[0]);
await page.goto(base + '#sales'); await page.click('[data-tabs="dup"]'); await page.waitForTimeout(300); await shot('34a-dup.png');
await page.click('[data-dupall="KEEP"]'); await page.waitForTimeout(300);
console.log('dup:', (await txt('.alert')).slice(0, 160));
await page.goto(base + '#close'); await page.waitForSelector('.result'); await shot('34-close.png');
console.log('CLOSE:', await txt('.result'), '|', await txt('.kpis'));
// F-01: upstream change after STEP 5 must make it OUTDATED and block the close
await page.goto(base + '#gl'); await page.waitForSelector('#f-gl');
const g627 = await page.inputValue('input[name=gl627]');
await page.fill('input[name=gl627]', '26.300'); await page.click('#f-gl button[type=submit]'); await page.waitForTimeout(300);
console.log('ambiguous number rejected:', (await page.textContent('#toasts')).includes('không rõ'));
await page.fill('input[name=gl627]', String(+g627 + 1000)); await page.click('#f-gl button[type=submit]'); await page.waitForTimeout(500);
await page.goto(base + '#close'); await page.waitForSelector('.result');
console.log('after GL edit:', (await txt('main')).match(/Chưa đóng được:.{0,140}/)?.[0]);
await page.goto(base + '#gl'); await page.fill('input[name=gl627]', g627); await page.click('#f-gl button[type=submit]'); await page.waitForTimeout(300);
await page.goto(base + '#step4'); await page.click('[data-act=run-step4]'); await page.waitForTimeout(1500);
await page.goto(base + '#step5'); await page.click('[data-act=s5-run]'); await page.waitForTimeout(1500);
await page.goto(base + '#close'); await page.waitForSelector('.result');
await page.click('[data-act=s5-hist]'); await page.waitForTimeout(1200);
// FAST tie: before entry the close is blocked; enter the web figures but 632 off by 1.000 → approve with a note
console.log('close before FAST:', ((await txt('main')).match(/Chưa đóng được:.{0,120}/) || [''])[0]);
await page.click('[data-tabh="fast"]'); await page.waitForSelector('#f-fast');
const engVals = await page.$$eval('#f-fast tbody tr', (trs) => trs.map((tr) => tr.children[2].textContent.replace(/\./g, '').replace(',', '.')));
for (const [i, k] of ['a154', 'a155', 'a632', 'a511'].entries()) await page.fill(`#f-fast input[name=${k}]`, k === 'a632' ? String(Math.round(+engVals[i]) - 1000) : String(Math.round(+engVals[i])));
await page.click('#f-fast button[type=submit]'); await page.waitForTimeout(400);
console.log('FAST after entry:', ((await txt('main')).match(/\d+ tài khoản lệch FAST/) || ['(khớp)'])[0]);
await page.fill('#f-fast-ok input[name=note]', 'Kiểm thử: chênh làm tròn bút toán 632'); await page.click('#f-fast-ok button'); await page.waitForTimeout(400);
console.log('FAST approved:', ((await txt('main')).match(/Chênh lệch đã được xác nhận.{0,60}/) || ['?'])[0]);
await page.goto(base + '#cc'); await page.waitForTimeout(400);
for (const k of ['Cầu nối TK 154', 'Cầu nối TK 155', 'thiếu / sai ngày', 'cảnh báo kiểm tra dữ liệu bán', 'Hệ S: xuất', 'dự phòng rộng', 'Giá bán cần xác nhận', 'ERP map: vật tư đổi']) console.log('CP', k, '|', ((await txt('main')).match(new RegExp(k + '.{0,90}')) || ['(không thấy)'])[0]);
await page.goto(base + '#close'); await page.waitForSelector('.result');
await page.click('[data-act=s5-close]'); await page.waitForTimeout(1200);
console.log('after close:', await txt('.result'));
await shot('35-closed.png');
// F-02: closed period is read-only everywhere
await page.goto(base + '#gl'); await page.waitForSelector('#f-gl');
console.log('closed: GL inputs disabled =', await page.isDisabled('input[name=gl627]'));
await page.goto(base + '#p3b'); await page.click('[data-tab3b="input"]'); await page.waitForTimeout(300);
console.log('closed: 3B editable cells =', await page.locator('#t3b td.ed input, #t3b td.ed select').count());
await page.goto(base + '#step4'); await page.click('[data-act=run-step4]'); await page.waitForTimeout(300);
console.log('closed: run step4 blocked =', (await page.textContent('#toasts')).includes('đã đóng'));
await page.goto(base + '#close'); await page.click('[data-act=s5-reopen]'); await page.waitForTimeout(500);
await page.goto(base + '#gl'); await page.waitForSelector('#f-gl');
console.log('reopened: GL inputs disabled =', await page.isDisabled('input[name=gl627]'));
await page.goto(base + '#close'); await page.click('[data-act=s5-close]'); await page.waitForTimeout(800);
console.log('re-closed:', await txt('.result'));
await page.evaluate(() => { window.prompt = () => '2026-09'; });
await page.click('[data-act=new-period]'); await page.waitForTimeout(2000);
await page.goto(base + '#fgopen'); await page.waitForSelector('.kpis');
console.log('SEP open:', await txt('.result'), '|', await txt('.kpis'));
await page.click('[data-act=s5-validate]'); await page.waitForTimeout(800);
console.log('SEP validate:', await txt('.result'));
await shot('36-sep-open.png');
await page.goto(base + '#close'); await page.waitForSelector('.kpis');
console.log('SEP hist:', await txt('.kpis'));
await page.goto(base + '#cc'); await page.waitForTimeout(400);
console.log('SEP cc:', (await txt('main')).slice(0, 300));
await page.emulateMedia({ colorScheme: 'dark' }); await page.goto(base + '#step5'); await page.waitForTimeout(400); await shot('37-dark.png');
await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base + '#fgopen'); await page.waitForTimeout(400); await shot('38-mobile.png');
console.log('errors:', errors.join('\n') || 'none');
await browser.close();
if (errors.length) process.exit(1);
