// Browser check for Phase 2 screens after migrating the workbook.
import { chromium } from 'playwright';
import path from 'node:path';
const [, , base0, wbPath, outDir] = process.argv;
const base = base0 + '?sandbox=1';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_TUNNEL')) errors.push('console: ' + m.text()); });
page.on('dialog', async (d) => { await d.accept(); });
await page.goto(base + '#settings');
await page.waitForSelector('#f-xlsm', { state: 'attached' });
const t0 = Date.now();
await page.setInputFiles('#f-xlsm', wbPath);
await page.waitForSelector('#mig table', { timeout: 240000 });
console.log('migrate secs', (Date.now() - t0) / 1000);
console.log((await page.textContent('#mig')).replace(/\s+/g, ' '));
const shot = async (n) => page.screenshot({ path: path.join(outDir, n), fullPage: false });
const txt = async (sel) => (await page.textContent(sel)).replace(/\s+/g, ' ');
await page.goto(base + '#cc'); await page.waitForTimeout(400); await shot('20-cc.png');
console.log('CC:', (await txt('main')).slice(0, 900));
await page.goto(base + '#p3b'); await page.waitForSelector('.kpis'); await shot('21-3b.png');
console.log('3B:', (await txt('.ph')).slice(0, 200), '|', await txt('.kpis'));
for (const t of ['input', 'detail', '632', 'wip', 'map']) { await page.click(`[data-tab3b="${t}"]`); await page.waitForTimeout(250); }
await shot('22-3b-map.png');
await page.goto(base + '#sales'); await page.waitForSelector('.kpis'); await page.click('[data-tabs="pm"]'); await page.waitForTimeout(300); await shot('23-pm.png');
console.log('SALES:', await txt('.kpis'));
for (const t of ['db', 'so', 'manual', 'import']) { await page.click(`[data-tabs="${t}"]`); await page.waitForTimeout(250); }
await page.goto(base + '#gl'); await page.waitForSelector('#f-gl'); await shot('24-gl.png');
await page.goto(base + '#step4'); await page.waitForSelector('.result'); await shot('25-step4.png');
console.log('STEP4:', (await txt('.result')), '|', await txt('.kpis'));
await page.click('[data-act=run-step4]'); await page.waitForTimeout(1500);
console.log('STEP4 rerun:', (await txt('.result')), '|', (await txt('main')).match(/Engine.{0,120}/)?.[0]);
await page.click('[data-tab4="rec"]'); await page.waitForTimeout(300); await shot('26-rec.png');
await page.click('[data-tab4="lot"]'); await page.waitForTimeout(300);
console.log('LOT:', (await txt('#t4')).slice(0, 160));
await page.goto(base + '#p3b'); await page.click('[data-act="3b-build"]'); await page.waitForTimeout(1500);
console.log('3B rebuild:', await txt('.result'));
await page.emulateMedia({ colorScheme: 'dark' });
await page.goto(base + '#step4'); await page.waitForSelector('.result'); await shot('27-dark-step4.png');
await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base + '#gl'); await page.waitForTimeout(300); await shot('28-mobile-gl.png');
await page.setViewportSize({ width: 1440, height: 900 });
await page.evaluate(() => { window.prompt = () => '2026-09'; });
await page.click('[data-act=new-period]'); await page.waitForTimeout(1500);
await page.goto(base + '#gl'); await page.waitForSelector('#f-gl');
console.log('GL sep:', (await txt('#f-gl')).slice(0, 200));
await page.goto(base + '#sales'); await page.waitForSelector('.kpis');
console.log('SALES sep:', await txt('.kpis'));
console.log('errors:', errors.join('\n') || 'none');
await browser.close();
if (errors.length) process.exit(1);
