// Browser check for 5B · Xử lý Rework: pending rework stays in 154; dispositions (return to FG / write-off) after RUN FIFO.
// node test/e2e-rework.mjs <base-url> <costing.xlsm> <outDir>
import { chromium } from 'playwright';
import path from 'node:path';
const [, , base0, wbPath, outDir] = process.argv;
const base = base0 + '?sandbox=1';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_TUNNEL')) errors.push('console: ' + m.text()); });
page.on('dialog', async (d) => { await d.accept(d.type() === 'prompt' ? 'test' : undefined); });
const txt = async (sel) => (await page.textContent(sel)).replace(/\s+/g, ' ');
await page.goto(base + '#settings');
await page.waitForSelector('#f-xlsm', { state: 'attached' });
await page.setInputFiles('#f-xlsm', wbPath);
await page.waitForSelector('#mig table', { timeout: 240000 });
await page.goto(base + '#step5'); await page.waitForSelector('.result'); await page.click('[data-act=s5-run]'); await page.waitForTimeout(1500);
await page.goto(base + '#rwflow'); await page.waitForSelector('.result');
console.log('5B before:', await txt('.result'), '|', await txt('.kpis'));
console.log('5B ERP note:', ((await txt('main')).match(/Kỳ này: ERP .{0,80}/) || ['?'])[0]);
await page.click('[data-tabrw="erp"]'); await page.waitForTimeout(300);
console.log('5B ERP checks:', JSON.stringify(((await txt('#rw-box')).match(/BẤT THƯỜNG: ERP|Khớp NVL|ERP thấp hơn NVL|Trong khoảng NVL/g) || []).reduce((o, k) => ({ ...o, [k]: (o[k] || 0) + 1 }), {})));
console.log('5B ERP box:', ((await txt('main')).match(/Kỳ này có .{0,260}/) || ['?'])[0]);
await page.screenshot({ path: path.join(outDir, '70-rework-erp.png') });
await page.click('[data-tabrw="pending"]'); await page.waitForTimeout(300);
// write off the first pending line to 811, return the second to FG
await page.click('#rw-t tbody tr[data-v="0"]'); await page.waitForSelector('#f-rw');
await page.selectOption('#f-rw select[name=st]', 'WRITTEN OFF'); await page.selectOption('#f-rw select[name=acc]', '811');
await page.fill('#f-rw input[name=note]', 'Kiểm thử: không sửa được'); await page.click('#f-rw button[type=submit]'); await page.waitForTimeout(400);
await page.click('#rw-t tbody tr[data-v="0"]'); await page.waitForSelector('#f-rw');
await page.selectOption('#f-rw select[name=st]', 'RETURNED TO FG'); await page.fill('#f-rw input[name=note]', 'Kiểm thử: trả về kho'); await page.click('#f-rw button[type=submit]'); await page.waitForTimeout(400);
console.log('5B after dispositions:', await txt('.result'), '|', (await page.textContent('#toasts')).slice(-120));
await page.goto(base + '#step5'); await page.waitForSelector('.result');
console.log('5.2 stale:', ((await txt('main')).match(/STEP 5 OUTDATED:.{0,90}/) || ['(not stale)'])[0]);
await page.click('[data-act=s5-run]'); await page.waitForTimeout(1500);
console.log('5.2 rerun:', await txt('.result'));
console.log('5.2 non-pass:', JSON.stringify(await page.$$eval('table.cp tr', (trs) => trs.map((tr) => tr.textContent.replace(/\s+/g, ' ').trim()).filter((t) => /BLOCK|CHECK|RERUN|NOT RUN/.test(t)).slice(0, 8))));
await page.goto(base + '#rwflow'); await page.waitForSelector('.result');
console.log('5B after FIFO:', await txt('.result'), '|', await txt('.kpis'));
await page.click('[data-tabrw="roll"]'); await page.waitForTimeout(300);
console.log('5B roll:', ((await txt('#rw-box')).match(/Đầu kỳ.{0,400}/) || ['?'])[0]);
await page.screenshot({ path: path.join(outDir, '71-rework-roll.png') });
await page.goto(base + '#cc'); await page.waitForTimeout(300);
for (const k of ['5BXử lý Rework', 'Cầu nối TK 155', 'Cầu nối TK 154', 'Rework treo từ', 'SL rework = SL', 'FIFO \\+ B/F']) console.log('CC', k, '|', ((await txt('main')).match(new RegExp(k + '.{0,100}')) || ['(không thấy)'])[0]);
await page.goto(base + '#close'); await page.waitForSelector('.result'); await page.click('[data-act=s5-hist]'); await page.waitForTimeout(1200);
console.log('history after dispositions:', (await page.textContent('#toasts')).slice(-150), '|', await txt('.result'));
await page.click('[data-tabh="fast"]'); await page.waitForSelector('#f-fast');
console.log('FAST 632:', JSON.stringify(await page.$$eval('#f-fast tbody tr', (trs) => trs.filter((tr) => /^(154|155|632)$/.test(tr.children[0].textContent.trim())).map((tr) => [tr.children[0].textContent.trim(), tr.children[2].textContent.trim()]))));
console.log('errors:', errors.length ? errors.join(' | ') : 'none');
await browser.close();
