import { chromium } from 'playwright';
import path from 'node:path';
const [, , base0, wbPath, outDir] = process.argv;
const base = base0 + '?sandbox=1';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('dialog', async (d) => { console.log('dialog:', d.message().slice(0, 100)); await d.accept(); });
await page.goto(base + '#settings');
await page.waitForSelector('#f-xlsm', { state: 'attached' });
const t0 = Date.now();
await page.setInputFiles('#f-xlsm', wbPath);
await page.waitForSelector('#mig table', { timeout: 240000 });
console.log('migrate secs', (Date.now() - t0) / 1000);
console.log((await page.textContent('#mig')).replace(/\s+/g, ' '));
await page.screenshot({ path: path.join(outDir, '10-migrate.png') });
await page.emulateMedia({ colorScheme: 'dark' });
await page.goto(base + '#rework'); await page.waitForSelector('#t-rw .vt-table');
await page.screenshot({ path: path.join(outDir, '11-dark-rework.png') });
// next period roll-forward
await page.evaluate(() => { window.prompt = () => '2026-09'; });
await page.click('[data-act=new-period]');
await page.waitForTimeout(1500);
await page.goto(base + '#opening'); await page.waitForSelector('.kpis');
console.log('opening sep:', (await page.textContent('.kpis')).replace(/\s+/g, ' '));
await page.goto(base + '#rework'); await page.waitForTimeout(500);
console.log('rework sep:', (await page.textContent('main')).replace(/\s+/g, ' ').slice(0, 300));
console.log('errors:', errors.join('\n') || 'none');
await browser.close();
if (errors.length) process.exit(1);
